[package]
name = "alfred-ai-callback"
version = "0.1.0"
edition = "2021"

[dependencies]
alfred-rs = { path = "../alfred-rs" }
env_logger = "0.11"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
